"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { AttemptResults } from "@/components/attempt-results";
import { AssignmentSkeleton } from "@/components/skeletons";
import { api, AssignmentStatus, SubmitAnswer } from "@/lib/api";

// Question/option text is plain markdown source (bold, code, lists, etc.)
// generated by the LLM — rendered inline (no wrapping <p>) so it fits inside
// a CardTitle/label without breaking their layout.
function InlineMarkdown({ children }: { children: string }) {
  return (
    <ReactMarkdown remarkPlugins={[remarkGfm]} components={{ p: ({ children }) => <>{children}</> }}>
      {children}
    </ReactMarkdown>
  );
}

interface AssignmentRunnerProps {
  slug: string;
  assignmentId: number | null;
  // Distinguishes the React Query cache entry when the same chapter/module
  // id can back more than one assignment (e.g. a specific past chapter
  // version vs. the live/latest one) — otherwise paging between versions
  // would keep serving the first version's cached response. Defaults to
  // `assignmentId` (the prior single-cache-entry-per-id behavior).
  cacheKey?: string | number | null;
  fetchAssignment: () => Promise<AssignmentStatus>;
  resultsHref: (assignmentId: number, attemptId: number) => string;
}

export function AssignmentRunner({ slug, assignmentId, cacheKey, fetchAssignment, resultsHref }: AssignmentRunnerProps) {
  const router = useRouter();
  const queryClient = useQueryClient();
  const [answers, setAnswers] = useState<Record<number, string>>({});
  // Flipping to the question form to try again is a purely local, temporary
  // view state — never persisted. Closing and reopening this page always
  // lands back on the latest result, per design.
  const [retaking, setRetaking] = useState(false);

  const assignmentQuery = useQuery({
    queryKey: ["assignment", slug, cacheKey ?? assignmentId],
    queryFn: fetchAssignment,
    refetchInterval: (query) => (query.state.data?.status === "generating" ? 2000 : false),
  });
  const data = assignmentQuery.data;
  const realAssignmentId = data?.id ?? null;

  const attemptsQuery = useQuery({
    queryKey: ["attempts", slug, realAssignmentId],
    queryFn: () => api.listAttempts(slug, realAssignmentId as number),
    enabled: realAssignmentId !== null,
  });

  const submit = useMutation({
    mutationFn: async () => {
      // The assignment's own id (not the `assignmentId` prop, which is only
      // the chapter/module id used for the React Query cache key) is what
      // submitAttempt needs — getChapterAssignment's URL is keyed by
      // chapterId, not Assignment.id, so the real id has to come from the
      // fetch response itself. It's also what the results page URL needs
      // (module assignment ids are genuinely different from moduleId), so
      // carry it alongside the submit result rather than re-deriving it
      // later from a possibly-stale closure over assignmentQuery.data.
      if (!data?.questions || data.id === null) throw new Error("assignment not ready");
      const payload: SubmitAnswer[] = data.questions.map((q) => ({
        question_id: q.id, answer: answers[q.id] ?? "",
      }));
      const result = await api.submitAttempt(slug, data.id, payload);
      return { ...result, assignmentId: data.id };
    },
    onSuccess: (result) => {
      queryClient.invalidateQueries({ queryKey: ["attempts", slug, result.assignmentId] });
      setRetaking(false);
      router.push(resultsHref(result.assignmentId, result.attempt_id));
    },
  });

  if (assignmentQuery.isLoading) return <AssignmentSkeleton />;
  if (assignmentQuery.isError) return <p className="text-red-600">Failed to load assignment.</p>;
  if (data?.status === "generating") return (
    <div className="space-y-4">
      <AssignmentSkeleton />
      <p className="text-sm text-muted-foreground">
        Putting your assignment together — hold on a minute, it&apos;ll be ready shortly.
      </p>
    </div>
  );
  if (data?.status === "failed") return <p className="text-red-600">Assignment generation failed: {data.error}</p>;
  if (!data?.questions || realAssignmentId === null) return null;
  // Wait for the attempt history before deciding which view to show —
  // otherwise a learner with a prior attempt would briefly flash the blank
  // question form before it flips to their latest result.
  if (attemptsQuery.isLoading) return <AssignmentSkeleton />;
  if (attemptsQuery.isError) return <p className="text-red-600">Failed to load your attempt history.</p>;

  const attempts = attemptsQuery.data ?? [];
  const latest = attempts[0];

  if (latest && !retaking) {
    return (
      <div className="space-y-6">
        <AttemptResults slug={slug} assignmentId={realAssignmentId} attemptId={latest.id} />
        <Button variant="outline" onClick={() => { setAnswers({}); setRetaking(true); }}>
          Retake this assignment
        </Button>
        {attempts.length > 1 && (
          <div className="space-y-2 border-t border-black/10 pt-4 dark:border-white/10">
            <h3 className="text-sm font-medium text-zinc-600 dark:text-zinc-400">Past attempts</h3>
            <div className="space-y-1.5">
              {attempts.map((a, i) => (
                <Link
                  key={a.id}
                  href={resultsHref(realAssignmentId, a.id)}
                  className="flex items-center justify-between gap-2 rounded-md px-2 py-1.5 text-sm hover:bg-zinc-100 dark:hover:bg-zinc-900"
                >
                  <span>
                    Attempt {attempts.length - i}
                    {a.id === latest.id && <span className="text-zinc-500"> (latest)</span>}
                  </span>
                  <span className="flex items-center gap-2">
                    {a.status === "graded" && (
                      <Badge variant={a.passed ? "secondary" : "outline"}>
                        {Math.round((a.overall_score ?? 0) * 100)}%
                      </Badge>
                    )}
                    {a.status !== "graded" && <Badge variant="outline">{a.status}</Badge>}
                  </span>
                </Link>
              ))}
            </div>
          </div>
        )}
      </div>
    );
  }

  const allAnswered = data.questions.every((q) => (answers[q.id] ?? "").trim().length > 0);

  return (
    <div className="space-y-4">
      {latest && retaking && (
        <button type="button" onClick={() => setRetaking(false)} className="text-sm text-zinc-600 underline dark:text-zinc-400">
          ← Back to latest result
        </button>
      )}
      {data.questions.map((q) => (
        <Card key={q.id}>
          <CardHeader>
            <CardTitle className="text-base"><InlineMarkdown>{q.text}</InlineMarkdown></CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {q.type === "mcq" && q.options?.map((opt) => (
              <label key={opt} className="flex items-center gap-2 text-sm">
                <input
                  type="radio" name={`q-${q.id}`} value={opt}
                  checked={answers[q.id] === opt}
                  onChange={() => setAnswers((prev) => ({ ...prev, [q.id]: opt }))}
                />
                <InlineMarkdown>{opt}</InlineMarkdown>
              </label>
            ))}
            {q.type === "true_false" && ["true", "false"].map((opt) => (
              <label key={opt} className="flex items-center gap-2 text-sm">
                <input
                  type="radio" name={`q-${q.id}`} value={opt}
                  checked={answers[q.id] === opt}
                  onChange={() => setAnswers((prev) => ({ ...prev, [q.id]: opt }))}
                />
                {opt}
              </label>
            ))}
            {q.type === "free_text" && (
              <textarea
                className="w-full rounded-md border border-black/10 p-2 text-sm dark:border-white/10"
                value={answers[q.id] ?? ""}
                onChange={(e) => setAnswers((prev) => ({ ...prev, [q.id]: e.target.value }))}
              />
            )}
          </CardContent>
        </Card>
      ))}
      <Button disabled={!allAnswered || submit.isPending} onClick={() => submit.mutate()}>
        {submit.isPending ? "Submitting…" : "Submit"}
      </Button>
      {submit.isError && <p className="text-red-600">Failed to submit. Please try again.</p>}
    </div>
  );
}
