"use client";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

// Question/option text is plain markdown source (bold, code, lists, etc.)
// generated by the LLM — rendered inline (no wrapping <p>) so it fits inside
// a CardTitle/label without breaking their layout.
export function InlineMarkdown({ children }: { children: string }) {
  return (
    <ReactMarkdown remarkPlugins={[remarkGfm]} components={{ p: ({ children }) => <>{children}</> }}>
      {children}
    </ReactMarkdown>
  );
}
